# syntax=docker/dockerfile:1

FROM golang:1.21 AS builder

# Set destination for COPY
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . ./
RUN CGO_ENABLED=0 GOOS=linux go build -v -o /main /app/server/main.go

FROM alpine:3.17.2 as final

RUN addgroup -S apps && adduser -S appuser -G apps
USER appuser
WORKDIR /app

COPY --from=builder /main /main
EXPOSE 50051

CMD ["/main"]